# -*- coding: utf-8 -*-
"""STAGE A_QUIZ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZvK0xLJ0rPy8jRcNT2-RW2JcUKErWol
"""

#Importing relevant libraries
import pandas as pd
import numpy as np

#Importing and reading the dataset
url='http://bit.ly/HDSC-Dataset'
df=pd.read_csv(url)
df.head()

#Getting a description of the data
print(df.describe())
print('\n')
print(df.info)

"""The data consists of 29523 rows and 11 columns.

The data consists of the following columns:

- 'Record_id' : record id

- 'Utility_id_ferc1': Utility id assigned by the FERC

- 'Report_year': year of report

- 'Plant_name_ferc1': the name of the plant

- 'Fuel_type_code_pudl': the type of fuel

- 'Fuel_unit': the unit of fuel

- 'Fuel_qty_burned': the quantity of fuel burned

- 'Fuel_mmbtu_per_unit': the measure of energy per unit

- 'fuel_cost_per_unit_burned': the fuel cost per unit burned

- 'Fuel_cost_per_unit_delivered': the cost of fuel delivered per unit

- 'fuel_cost_per_mmbtu': the cost of fuel per mmbtu
"""

#Importing pandas profiling package
!pip install 'https://github.com/pandas-profiling/pandas-profiling/archive/master.zip'
import pandas_profiling

#Using Pandas Profiling Package
from pandas_profiling import ProfileReport
report = ProfileReport(df,title='Pandas Profiling Report'
    , html={"style": {"full_width": True}})
report

rep=report.to_file('electric_utilities_profiling.html')
rep

"""# **Questions related to the dataset**

## ***Which fuel type code has the lowest average fuel cost per unit burned***
"""

df.groupby('fuel_type_code_pudl').agg(average_fuel_cost_per_unit_burned=('fuel_cost_per_unit_burned', 'mean'))

"""The answer is __gas__

## ***Which features have the second and third lowest correlation with the Fuel Cost Per Unit Burned?***
"""

#Obtaining pairwise correlation with fuel_cost_per_unit_burned
df1=df['fuel_cost_per_unit_burned']
df.corrwith(df1).sort_values()

"""The answer is __fuel_qty_burned__ and __fuel_mmbtu_per_unit__

## ***What is the standard deviation and 75th percentile of the measure of energy per unit (Fuel_mmbtu_per_unit) in two decimal places?***

As seen from the pandas profiling package the answer is __10.60__ and __17.01__.Let us confirm using the line of code below
"""

df['fuel_mmbtu_per_unit'].describe().round(2)

"""## ***What is the skewness and kurtosis for the fuel quantity burned in two decimal places?***

From the pandas profiling package the answer is __15.85__ and __651.37__.Let us confirm using the code below:
"""

fuel_qty=df['fuel_qty_burned']
print('skewness:',fuel_qty.skew().round(2))
print('\n')
print('kurtosis:',fuel_qty.kurt().round(2))

"""## ***Which feature has missing values and what is the total number of missing value and percentage of the missing rows as a factor of the total number of rows in three decimal places?***

- As depicted from pandas profiling the column with missing values is __fuel_unit__ with __180__ missing entries.
- The missing values account for 0.1% of the overall column.
- Missing values in a categorical column can be imputed by the __mode__ function
- The missing values account for __0.61%__ of the overall number of rows as seen below:
"""

#Percentage of missing values as a % of total rows
print(((df.isnull().sum()/len(df))*100).round(3))
print('\n')
#Examining the dtype of feature variable
print(df['fuel_unit'].dtype)



"""## ***For the fuel type coal, what is the percentage change in the fuel cost per unit burned in 1998 compared to 1994?***"""

mm=df[['fuel_type_code_pudl','fuel_cost_per_unit_burned']] [df['report_year'] == 1994]
dd=df[['fuel_type_code_pudl','fuel_cost_per_unit_burned']] [df['report_year'] == 1998]
print(mm.count())
print(dd.count())

change=(1235-1107)/1235
change

"""## ***Which year has the highest average fuel cost per unit delivered?***"""

df.groupby('report_year').agg(average_fuel_cost_per_unit_delivered=('fuel_cost_per_unit_delivered', 'mean'))

"""The answer is __1997__"""